version: '3.7'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./server
    depends_on:
      - redis
      - postgres
    env_file:
      - .env
    image: mets-server:1.0.1
    container_name: mets-server
    ports:
      - 8080:8080
    tmpfs:
      - /tmp
    volumes:
      - ./ui:/service/ui:cached

  postgres:
    image: postgres:${PG_MAJOR:-14}-alpine
    container_name: mets-postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DB_DATABASE=development
      - DB_USERNAME=mets
      - DB_PASSWORD=mets-development
    expose:
      - 5432
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./db/init-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh

  redis:
    image: redis:5.0.5-alpine
    container_name: mets-redis
    volumes:
      - redis:/data
    ports:
      - 6379

volumes:
  postgres:
    driver: local
  redis:
