version: '3'

dotenv: ['.env']

tasks:
  db:seed:
    desc: Seed local database
    deps: [db:start]
    env:
      DB_HOST: localhost
    cmds:
      - go run ./cmd/seeder

  db:start:
    desc: Start local DB in background
    deps: [docker:setup]
    status:
      - docker ps | grep mets-postgres >/dev/null 2>&1
    cmds:
      - docker compose up -d postgres

  docker:setup:
    desc: Build Docker resources
    cmds:
      - docker compose build server
    status:
      - docker inspect --type=image {{.DEV_CONTAINER_TAG}} >/dev/null 2>&1
    sources:
      - Dockerfile
      - docker-compose.yml
      - .dockerignore
      - go.mod
      - go.sum
      - cmd/**/*.go
      - pkg/**/*.go

  docker:teardown:
    desc: Remove Docker containers, images, volumes, and networks (if any)
    cmds:
      - docker compose down --volumes
      - docker rmi {{.DEV_CONTAINER_TAG}}

  start:
    desc: Start development server
    deps: [docker:setup]
    cmds:
      - docker compose up

  stop:
    desc: Stop development server
    cmds:
      - docker compose stop

  test:
    cmds:
      - go test -v

  up:
    desc: Start dev server in background
    deps: [docker:setup]
    cmds:
      - docker compose up -d
