version: '3'

dotenv: ['.env']

tasks:
  db:init:dev:
    cmds:
      - go run ./cmd/migrate -dsn {{.DB_FILE}}
      - sqlite3 {{.DB_FILE}} '.read data/seeds.sql'
    generates:
      - "{{.DB_FILE}}"
    sources:
      - cmd/migrate/main.go
      - data/seeds.sql

  test:
    cmds:
      - go test -v
